### PR TITLE
Cleaned up package files, updated readme, added an Express API and added demo on Http

### PR DESCRIPTION
**Pull request by sravikiran**
1. Removed typing files of libraries
2. Updated readme with details of tsd install
3. Added an Express API to demonstrate usage of APIs
4. Modified DummyService to use Http
5. Modified Sidebar to use the DummyService AJAX calls
6. Added additional typings to scripts folder

### CODE REVIEW

**Comment by sravikiran** [comment]
Aim of this PR is to update version of Angular 2 and to keep the package/library files away from the repo. Let me know if you have any comments.

FYI: If this PR is merged, I will mention this project in an article that I am writing on Angular 2 for <a href="http://www.sitepoint.com">SitePoint</a>. If you have any concerns in merging it because of the bigger changes, I will mention my fork.

**Comment by EladRK** [comment]
hey @sravikiran ,

thanks for the PR, looks like a lot of good work. i'm working on the merge now as it's quite a lot of changes. 

thanks,
Elad

**Comment by EladRK** [comment]
merged, thanks!

**Comment by EladRK** [comment]
why did u remove the open browser task from gulp btw?

**Comment by sravikiran** [comment]
@EladRK I commented it for some testing and forgot to uncomment. Shall I raise a separate PR for that or, will you update it?

**Comment by EladRK** [comment]
if u can raise a PR it would be great. we're continuing development over it this sprint :)

**Comment by sravikiran** [comment]
OK. I will raise the PR some time today
Are you planning to keep updating this seed project for the new alpha releases of Angular 2? If so, I can help you with that.

**Pull request merged**
